# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 623afb853f35796689279524a2adca944ed093d4d89e0f207d5ecbc6f25eef8440801266f6005a068a3c8da0549fc14cf59d965a431a4b6c51c76697e313a759

test:
  secret_key_base: 86799afaa585510d9bccdeaedb05387533496864fe2e8826098b20319d5f1d24bb5822f495eaabc149ecf95977c9def5a41a173f15b8fae9e95f73bdc18e8714

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
